[model]
path = "../models/lost_empire/lost_empire.obj"

[camera]
type = "fpv"
position = [-7.4, 30.8, 12.7]
up = [0.0, 0.0, 1.0]
pitch = 87.4295
yaw = -180.382
fovy = 39.6
sensitivity = 0.05
speed = 5.0